# Generated by Django 4.2.13 on 2024-06-25 08:54

from django.db import migrations


def create_new_prices(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for phone in smartphones:
        phone.price = len(phone.brand) * 120

    smartphone_model.objects.bulk_update(smartphones, ['price'])


def reversed_create_new_prices(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for phone in smartphones:
        phone.rarity = smartphone_model._meta.get_field('price').default

    smartphone_model.objects.bulk_update(smartphones, ['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            create_new_prices, reverse_code=reversed_create_new_prices
        ),
    ]
