# Generated by Django 4.2.13 on 2024-06-25 09:09

from django.db import migrations


def create_new_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for phone in smartphones:
        if phone.price >= 750:
            phone.category = 'Expensive'
        else:
            phone.category = 'Cheap'

    smartphone_model.objects.bulk_update(smartphones, ['category'])


def reversed_create_new_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for phone in smartphones:
        phone.category = smartphone_model._meta.get_field('category').default


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_smartphone_manual_migration'),
    ]

    operations = [
        migrations.RunPython(create_new_category, reverse_code=reversed_create_new_category),
    ]
