# Generated by Django 4.2.13 on 2024-06-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration_in_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration in Days'),
        ),
    ]
