# Generated by Django 4.2.13 on 2024-06-22 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_project_duration_in_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 6, 22), null=True, verbose_name='Start Date'),
        ),
    ]
