# Generated by Django 4.2.13 on 2024-06-23 18:20
import random
from django.db import migrations


def add_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    all_products = Product.objects.all()
    all_barcodes = random.sample(
        range(100000000, 100000000),
        len(all_products)
    )
    for i in range(len(all_products)):
        curr_product = all_products[i]
        curr_product.barcode = all_barcodes[i]
        curr_product.save()


def reverse_add_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    all_products = Product.objects.all()

    for product in all_products:
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_code=reverse_add_barcode)
    ]
