# Generated by Django 4.2.13 on 2024-06-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_barcode'),
        ('main_app', '0005_auto_20240623_2120'),
    ]

    operations = [
    ]
